#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Inventory;
    
    #line 1 "..\..\Views\Tasks\Transfer\Verification.cshtml"
    using MixERP.Inventory.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Transfer/Verification.cshtml")]
    public partial class _Views_Tasks_Transfer_Verification_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Transfer_Verification_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Transfer\Verification.cshtml"
  
    ViewBag.Title = "Inventory Transfer Verification";
    Layout = ViewBag.InventoryLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Tasks\Transfer\Verification.cshtml"
Write(Html.FinancePartialView("Shared/Verification.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral(@"

<script>
    window.prepareVerification({
        Title: ""Inventory Transfer Verification"",
        AddNewText: ""Add New"",
        AddNewUrl: ""/dashboard/inventory/tasks/inventory-transfers/new"",
        Book: ""Inventory Adjustment"",
        ChecklistUrl: ""/dashboard/inventory/tasks/transfers/checklist/{tranId}"",
        AdviceButtons: [
            {
                Title: ""View Transfer"",
                Href: ""javascript:void(0);"",
                OnClick: ""showTransfer({tranId});""
            }
        ]
    });

    function showAdjustment(tranId) {
        $("".advice.modal iframe"").attr(""src"",
            `/dashboard/reports/source/Areas/MixERP.Inventory/Reports/Transfer.xml?transaction_master_id=${tranId}`);

        setTimeout(function() {
            $("".advice.modal"")
                .modal('setting', 'transition', 'horizontal flip')
                .modal(""show"");

        }, 300);
    };
</script>");

        }
    }
}
#pragma warning restore 1591
