#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Setup\OpeningInventory\New.cshtml"
    using Frapid.ApplicationState.Cache;
    
    #line default
    #line hidden
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Inventory;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/OpeningInventory/New.cshtml")]
    public partial class _Views_Setup_OpeningInventory_New_cshtml : System.Web.Mvc.WebViewPage<MixERP.Inventory.ViewModels.OpeningInventoryViewModel>
    {
        public _Views_Setup_OpeningInventory_New_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Setup\OpeningInventory\New.cshtml"
  
    ViewBag.Title = "Opening Inventory";
    Layout = ViewBag.InventoryLayoutPath;
    var meta = AppUsers.GetCurrent();

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Setup\OpeningInventory\New.cshtml"
 if (!Model.MultipleInventoryAllowed && Model.HasOpeningInventory)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"ui attached segment\"");

WriteLiteral(" style=\"min-height: 100%; padding: 3em;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Opening Inventory</div>\r\n        <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"ui positive message\"");

WriteLiteral(">Opening inventory has already been entered for this office.</div>\r\n\r\n        <a");

WriteLiteral(" href=\"/dashboard/inventory/setup/opening-inventory\"");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(">Okay</a>\r\n    </div>\r\n");

            
            #line 18 "..\..\Views\Setup\OpeningInventory\New.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <style>\r\n        #dashboard-container {\r\n            padding: 0 !important;\r\n" +
"        }\r\n\r\n        iframe {\r\n            background-color: white;\r\n           " +
" width: 100%;\r\n            height: 500px;\r\n            border: none;\r\n          " +
"  display: none;\r\n        }\r\n\r\n        .inverted.header, .inverted.form {\r\n     " +
"       background: transparent !important;\r\n        }\r\n\r\n        input.invoice.n" +
"umber.for.reprint {\r\n            background: transparent !important;\r\n          " +
"  border: 1px solid #555 !important;\r\n            color: #eee !important;\r\n     " +
"   }\r\n\r\n        .inverted.info.message {\r\n            background-color: #B3A12E " +
"!important;\r\n            border: 1px solid #B3A12E !important;\r\n            colo" +
"r: #fff !important;\r\n        }\r\n\r\n        .info {\r\n            padding: 0.25em 0" +
".5em;\r\n            display: inline-block;\r\n            margin: 1px;\r\n           " +
" -ms-border-radius: 4px;\r\n            border-radius: 4px;\r\n            font-weig" +
"ht: bold;\r\n            text-transform: uppercase;\r\n            font-size: 0.92em" +
";\r\n        }\r\n\r\n        .office.info {\r\n            background-color: #D65302;\r\n" +
"        }\r\n\r\n        .user.info {\r\n            background-color: #68A800;\r\n     " +
"   }\r\n\r\n        .area.info {\r\n            background-color: #02B3D6;\r\n        }\r" +
"\n\r\n        .counter.info {\r\n            background-color: #AC02D6;\r\n        }\r\n\r" +
"\n\r\n\r\n        .status.head {\r\n            background-color: #444;\r\n            pa" +
"dding: 1em;\r\n            cursor: pointer;\r\n        }\r\n\r\n        .inline.blocks >" +
" .item {\r\n            display: inline-block !important;\r\n            padding: 2p" +
"x;\r\n        }\r\n\r\n        .two.inline.blocks > .item {\r\n            width: 50%;\r\n" +
"        }\r\n\r\n        .three.inline.blocks > .item {\r\n            width: 33%;\r\n  " +
"      }\r\n\r\n        .four.inline.blocks > .item {\r\n            width: 25%;\r\n     " +
"   }\r\n\r\n        .status.head .left {\r\n            display: inline-block;\r\n      " +
"      width: 50%;\r\n        }\r\n\r\n        .status.head .right {\r\n            displ" +
"ay: inline-block;\r\n            text-align: right;\r\n            width: 50%;\r\n    " +
"    }\r\n\r\n        .item.list {\r\n            background-color: #333;\r\n            " +
"cursor: pointer;\r\n            text-align: center;\r\n        }\r\n\r\n            .ite" +
"m.list .item {\r\n                display: inline-flex;\r\n                backgroun" +
"d-color: #333;\r\n                margin: 4px;\r\n                height: 280px;\r\n  " +
"              padding: 0.5em;\r\n                width: 200px;\r\n                cu" +
"rsor: pointer;\r\n            }\r\n\r\n                .item.list .item:hover {\r\n     " +
"               background-color: #444;\r\n                }\r\n\r\n                .it" +
"em.list .item .info {\r\n                    overflow: hidden;\r\n                }\r" +
"\n\r\n                .item.list .item .photo {\r\n                    position: rela" +
"tive;\r\n                    top: -16px;\r\n                    left: -2px;\r\n       " +
"             width: 180px;\r\n                    height: 270px;\r\n                " +
"}\r\n\r\n\r\n                .item.list .item:hover img {\r\n                    filter:" +
" grayscale(0%) !important;\r\n                }\r\n\r\n                .item.list .ite" +
"m .info .photo img {\r\n                    height: 390px;\r\n                    fi" +
"lter: grayscale(70%);\r\n                }\r\n\r\n                .item.list .item .in" +
"fo .name {\r\n                    font-size: 1.4em;\r\n                    font-weig" +
"ht: 100;\r\n                    position: relative;\r\n                    z-index: " +
"1;\r\n                    top: -5.5em;\r\n                    line-height: 1.2em;\r\n " +
"                   text-align: center;\r\n                    text-shadow: 2px 2px" +
" 10px black;\r\n                }\r\n\r\n                .item.list .item .info .price" +
" {\r\n                    font-size: 3em;\r\n                    font-weight: 100 !i" +
"mportant;\r\n                    text-align: right;\r\n                    position:" +
" relative;\r\n                    z-index: 1;\r\n                    top: 0.7em;\r\n  " +
"                  text-shadow: -2px 3px 10px #000;\r\n                    color: #" +
"eee;\r\n                }\r\n\r\n\r\n        .category.list {\r\n            padding: 4px;" +
"\r\n            text-align: center;\r\n            background-color: #555;\r\n        " +
"}\r\n\r\n            .category.list .filter {\r\n                text-align: right;\r\n " +
"               display: inline-block;\r\n            }\r\n\r\n            .category.li" +
"st .category, .cat.filter {\r\n                display: inline-block;\r\n           " +
"     background-color: #555;\r\n                color: white;\r\n                pad" +
"ding: 4px 12px;\r\n                margin: 2px;\r\n                border-radius: 12" +
"px;\r\n                text-transform: uppercase;\r\n                font-size: 0.9e" +
"m;\r\n                letter-spacing: 1px;\r\n                cursor: pointer;\r\n    " +
"            text-shadow: 0 0 2px white;\r\n            }\r\n\r\n            .category." +
"list .cat.filter {\r\n                background-color: #444;\r\n            }\r\n\r\n  " +
"          .category.list .category.selected, .category.list .category:hover {\r\n " +
"               background-color: #78AD05;\r\n            }\r\n\r\n            .categor" +
"y.list .cat.filter:hover {\r\n                background-color: #FA6400 !important" +
";\r\n            }\r\n\r\n        .search.panel {\r\n            background-color: #666;" +
"\r\n            padding: 1em;\r\n            text-align: center;\r\n        }\r\n\r\n     " +
"       .search.panel input {\r\n                text-align: center;\r\n             " +
"   font-size: 1.1em;\r\n                background-color: transparent;\r\n          " +
"      border: 1px solid #999;\r\n                border-radius: 2em;\r\n            " +
"    text-transform: uppercase;\r\n                height: 2em;\r\n                wi" +
"dth: 20em;\r\n            }\r\n\r\n\r\n        .opening.items .item {\r\n            backg" +
"round-color: #333;\r\n            padding: 3px 9px;\r\n            border-bottom: 1p" +
"x dotted #444;\r\n            cursor: pointer;\r\n            -webkit-user-select: n" +
"one; /* webkit (safari, chrome) browsers */\r\n            -moz-user-select: none;" +
" /* mozilla browsers */\r\n            -khtml-user-select: none; /* webkit (konque" +
"ror) browsers */\r\n            -ms-user-select: none; /* IE10+ */\r\n        }\r\n\r\n " +
"           .opening.items .item:nth-child(even) {\r\n                background-co" +
"lor: #373737 !important;\r\n            }\r\n\r\n            .opening.items .item:hove" +
"r {\r\n                background-color: #3a3a3a !important;\r\n            }\r\n\r\n   " +
"         .opening.items .item .block {\r\n                display: inline-block;\r\n" +
"                height: 82px;\r\n                overflow: hidden;\r\n            }\r" +
"\n\r\n                .opening.items .item .block img {\r\n                    height" +
": 82px;\r\n                }\r\n\r\n            .opening.items .item .photo.block {\r\n " +
"               width: 90px;\r\n                overflow: hidden;\r\n            }\r\n\r" +
"\n            .opening.items .item .number.block {\r\n                width: 120px;" +
"\r\n            }\r\n\r\n\r\n                .opening.items .item .number.block button {" +
"\r\n                    height: 100%;\r\n                    text-transform: upperca" +
"se;\r\n                    letter-spacing: 1px;\r\n                    font-weight: " +
"100;\r\n                }\r\n\r\n            .opening.items .item input {\r\n           " +
"     font-size: 1.3em;\r\n                margin: 0 0 0.3em 0;\r\n                ba" +
"ckground-color: #333;\r\n                border: 1px solid #555;\r\n                " +
"width: 100%;\r\n                padding: 4px 16px;\r\n                text-align: ri" +
"ght;\r\n                border-radius: 0.5em;\r\n            }\r\n\r\n            .openi" +
"ng.items .item .info.block {\r\n                width: calc(100% - 220px);\r\n      " +
"          padding: 1em;\r\n            }\r\n\r\n                .opening.items .item ." +
"info.block .price.info,\r\n                .opening.items .item .info.block .heade" +
"r {\r\n                    display: block;\r\n                }\r\n\r\n                ." +
"opening.items .item .info.block .header {\r\n                    font-size: 1.5em;" +
"\r\n                    font-weight: 100;\r\n                    text-transform: upp" +
"ercase;\r\n                }\r\n\r\n                .opening.items .item .info.block ." +
"price.info {\r\n                    padding-top: 4px;\r\n                }\r\n\r\n      " +
"          .opening.items .item .info.block .price.info\r\n                {\r\n     " +
"               font-size: 1.1em;\r\n                    text-align: left;\r\n       " +
"             padding: 0;\r\n                    text-transform: none;\r\n           " +
"         color: #fbd842;\r\n                }\r\n\r\n\r\n        .tender.info {\r\n       " +
"     background-color: #333;\r\n            width: 100%;\r\n            cursor: poin" +
"ter;\r\n            margin: 0 0 8px 0;\r\n            padding: 6px 0;\r\n        }\r\n\r\n" +
"\r\n            .tender.info:hover {\r\n                background-color: #3f3f3f;\r\n" +
"            }\r\n\r\n\r\n        .summary.items {\r\n            padding: 0.5em 1em;\r\n  " +
"          display: flex;\r\n        }\r\n\r\n            .summary.items > .item {\r\n   " +
"             display: inline-flex;\r\n                flex-direction: column;\r\n   " +
"             padding: 2px;\r\n            }\r\n\r\n        .two.summary.items > .item " +
"{\r\n            width: 48%;\r\n        }\r\n\r\n        .one.summary.items > .item {\r\n " +
"           width: 96%;\r\n        }\r\n\r\n        .summary.items > .item > .descripti" +
"on {\r\n            padding-bottom: 0.5em;\r\n            font-size: 0.9em;\r\n       " +
"     text-align: left;\r\n        }\r\n\r\n        .summary.items > .item > .money {\r\n" +
"            padding-top: 0.1em;\r\n            font-size: 3em;\r\n        }\r\n\r\n\r\n   " +
"     input.pan.number,\r\n        input.customer.name,\r\n        input.customer.add" +
"ress {\r\n            font-size: 12px !important;\r\n            padding: 8px !impor" +
"tant;\r\n        }\r\n\r\n        .customer.name.item {\r\n            width: 40% !impor" +
"tant;\r\n        }\r\n\r\n        .customer.address.item {\r\n            width: 30% !im" +
"portant;\r\n        }\r\n\r\n        .pan.number.item {\r\n            width: 25% !impor" +
"tant;\r\n        }\r\n\r\n        .inverted.dropdown,\r\n        .inverted.dropdown inpu" +
"t.search,\r\n        .inverted.dropdown .menu,\r\n        .inverted.dropdown .item,\r" +
"\n        .inverted.dropdown .message {\r\n            background-color: #555 !impo" +
"rtant;\r\n            color: #eee !important;\r\n            border: 1px solid #666 " +
"!important;\r\n        }\r\n\r\n            .inverted.dropdown .item.selected,\r\n      " +
"      .inverted.dropdown .item:hover {\r\n                background-color: #666 !" +
"important;\r\n            }\r\n\r\n        .summary.items input,\r\n        .summary.ite" +
"ms select {\r\n            background-color: #555 !important;\r\n            color: " +
"#eee !important;\r\n            border: 1px solid #666 !important;\r\n            pa" +
"dding: .87em;\r\n            border-radius: 0.4em;\r\n            width: 100%;\r\n    " +
"        -moz-appearance: none; /* Firefox */\r\n        }\r\n\r\n        select.invert" +
"ed {\r\n            background-color: #333;\r\n            border: 1px solid #555;\r\n" +
"            width: 100%;\r\n            padding: 0.55em 1em;\r\n            border-r" +
"adius: 0.5em;\r\n            -moz-appearance: none; /* Firefox */\r\n        }\r\n    " +
"</style>\r\n");

            
            #line 419 "..\..\Views\Setup\OpeningInventory\New.cshtml"




            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"ui attached inverted pos opening inventory segment\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui active inverted dimmer\"");

WriteLiteral(" id=\"POSDimmer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui large text loader\"");

WriteLiteral(">Doing something ...</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui grid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"eleven wide column\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"status head\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"left\"");

WriteLiteral(">\r\n                        <strong");

WriteLiteral(" class=\"title info\"");

WriteLiteral(">\r\n                            Opening Inventory\r\n                        </stron" +
"g>\r\n                        <span");

WriteLiteral(" class=\"office info\"");

WriteLiteral(" title=\"Current Branch Office\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 434 "..\..\Views\Setup\OpeningInventory\New.cshtml"
                       Write(meta.OfficeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                        <span");

WriteLiteral(" class=\"user info\"");

WriteLiteral(" title=\"You\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 437 "..\..\Views\Setup\OpeningInventory\New.cshtml"
                       Write(meta.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                        <span");

WriteLiteral(" class=\"area info\"");

WriteLiteral(" title=\"Current Area\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 440 "..\..\Views\Setup\OpeningInventory\New.cshtml"
                       Write(meta.OfficeCode);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                        <span");

WriteLiteral(" class=\"office info\"");

WriteLiteral(" title=\"Office Name\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 443 "..\..\Views\Setup\OpeningInventory\New.cshtml"
                       Write(meta.OfficeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                    </div>\r\n                </" +
"div>\r\n\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"category list\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"cat filter\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                        Clear\r\n                        <i");

WriteLiteral(" class=\"delete icon\"");

WriteLiteral("></i>\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"search panel\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"search\"");

WriteLiteral(" placeholder=\"Search ...\"");

WriteLiteral(" />\r\n\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"item list\"");

WriteLiteral(" id=\"POSItemList\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"five wide column\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"tender info\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"SummaryItems\"");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"amount item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Amount</div>\r\n                            <div");

WriteLiteral(" class=\"money\"");

WriteLiteral(">\r\n                                <span></span>\r\n                            </d" +
"iv>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"store item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Store</div>\r\n                            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"StoreSelect\"");

WriteLiteral("></select>\r\n                            </div>\r\n                        </div>\r\n " +
"                   </div>\r\n                    <div");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"value date item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Value Date</div>\r\n                            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" id=\"ValueDateInputDate\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"book date item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Book Date</div>\r\n                            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" id=\"BookDateInputDate\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                    <div");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"reference number item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Ref#</div>\r\n                            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ReferenceNumberInputText\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"memo item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Memo</div>\r\n                            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"StatementReferenceInputText\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                    <div");

WriteLiteral(" class=\"ui one column padded grid\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"column\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" id=\"CheckoutButton\"");

WriteLiteral(" class=\"ui green icon big button\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"cart icon\"");

WriteLiteral("></i>\r\n                                CHECKOUT\r\n                            </bu" +
"tton>\r\n                            <button");

WriteLiteral(" id=\"ClearScreenButton\"");

WriteLiteral(" class=\"ui red icon big button\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"delete icon\"");

WriteLiteral("></i>\r\n                                CLS\r\n                            </button>" +
"\r\n                        </div>\r\n                    </div>\r\n                </" +
"div>\r\n                <div");

WriteLiteral(" id=\"OpeningItems\"");

WriteLiteral(" class=\"opening items\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 525 "..\..\Views\Setup\OpeningInventory\New.cshtml"



            
            #line default
            #line hidden
WriteLiteral(@"    <script>
    $(""#OpeningItems .item"")
        .on(""contextmenu"",
            function (e) {
                e.preventDefault();
                var el = $(this);
                var defaultMenu = el.find("".info.block, .number.block"");
                var contextMenu = el.find("".context.menu"");

                defaultMenu.toggle();
                contextMenu.toggle();
            });
    </script>
");

            
            #line 540 "..\..\Views\Setup\OpeningInventory\New.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"    <script>
    var itemTemplate = `<div class=""item"" id=""pos-{ItemId}"" data-cost-price=""{CostPrice}"" data-photo=""{Photo}"" data-unit-id=""{UnitId}"" data-valid-units=""{ValidUnits}"" data-brand=""{BrandName}"" data-item-group=""{ItemGroupName}"" data-item-name=""{ItemName}"" data-item-code=""{ItemCode}"" data-item-id=""{ItemId}"" data-price=""{Price}"">
	<div class=""photo block"">
		<img src=""{Photo}"">
	</div>
	<div class=""info block"">
		<div class=""header"">{ItemName}</div>
		<div class=""price info"">
			<span class=""rate"">{CostPrice}</span>
			<span>&nbsp; x&nbsp; </span>
			<span class=""quantity"">1</span>
			<span>&nbsp; =&nbsp; </span>
			<span class=""amount""></span>
		</div>
		<div>
			<select class=""unit inverted"" data-item-id=""{ItemId}"">
			</select>
		</div>
	</div>
	<div class=""number block"">
		<input type=""text"" class=""price"" title=""Edit Price"" value=""{CostPrice}"">
		<input type=""text"" class=""quantity"" title=""Enter Quantity"" value=""1"">
		<button class=""ui red fluid button"" onclick=""removeItem(this);"" style=""display:none;"">Delete</button>
	</div>
</div>`
    </script>
");

            
            #line 567 "..\..\Views\Setup\OpeningInventory\New.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n    var products = [];\r\n    var metaUnits = [];\r\n\r\n    function fet" +
"chUnits() {\r\n        function request() {\r\n            var url = \"/api/forms/inv" +
"entory/units/all\";\r\n            return window.getAjaxRequest(url);\r\n        };\r\n" +
"\r\n        var ajax = request();\r\n\r\n        ajax.success(function (response) {\r\n " +
"           window.metaUnits = response;\r\n        });\r\n    };\r\n\r\n    function fet" +
"chProducts() {\r\n        function request() {\r\n            var url = \"/dashboard/" +
"inventory/items/stockable/view\";\r\n            return window.getAjaxRequest(url);" +
"\r\n        };\r\n\r\n        var ajax = request();\r\n\r\n        ajax.success(function (" +
"response) {\r\n            window.products = response;\r\n            $(document).tr" +
"igger(\"itemFetched\");\r\n        });\r\n    };\r\n\r\n    $(\".search.panel input\").keyup" +
"(function () {\r\n        var el = $(this);\r\n        var term = el.val();\r\n\r\n     " +
"   var categoryEl = $(\".category.list .selected.category\");\r\n        var categor" +
"y = \"\";\r\n\r\n        if (categoryEl.length) {\r\n            category = categoryEl.t" +
"ext();\r\n        };\r\n\r\n        displayProducts(category, term);\r\n\r\n        initia" +
"lizeClickAndAction();\r\n    });\r\n\r\n    $(\".search.panel input\").keydown(function " +
"(e) {\r\n        if (e.keyCode === 13) {\r\n            var item = $(\".item.list .it" +
"em:first\");\r\n\r\n            if (item.length) {\r\n                item.trigger(\"cli" +
"ck\");\r\n            };\r\n        };\r\n    });\r\n\r\n    window.fetchUnits();\r\n    wind" +
"ow.fetchProducts();\r\n\r\n    setTimeout(function () {\r\n        window.fetchProduct" +
"s();\r\n    }, 120000);\r\n\r\n    function removeItem(el) {\r\n        var confirmed = " +
"confirm(\"Are you sure?\");\r\n\r\n        if (!confirmed) {\r\n            return;\r\n   " +
"     };\r\n\r\n        el = $(el);\r\n        var container = el.parent().parent();\r\n " +
"       container.remove();\r\n        window.updateTotal();\r\n    };\r\n\r\n    $(docum" +
"ent).on(\"itemFetched\", function () {\r\n        $(\"#POSDimmer\").removeClass(\"activ" +
"e\");\r\n        displayProducts();\r\n        displayCategories();\r\n        initiali" +
"zeClickAndAction();\r\n    });\r\n\r\n\r\n    function initializeClickAndAction() {\r\n   " +
"     $(\"#POSItemList .item\").unbind(\"click\").bind(\"click\", function () {\r\n      " +
"      var el = $(this);\r\n            var costPrice = el.attr(\"data-cost-price\");" +
"\r\n            var photo = el.attr(\"data-photo\");\r\n\r\n            var barCode = el" +
".attr(\"data-barcode\");\r\n            var brand = el.attr(\"data-brand\");\r\n        " +
"    var unitId = el.attr(\"data-unit-id\");\r\n            var validUnits = el.attr(" +
"\"data-valid-units\");\r\n            var itemGroup = el.attr(\"data-item-group\");\r\n " +
"           var itemName = el.attr(\"data-item-name\");\r\n            var itemCode =" +
" el.attr(\"data-item-code\");\r\n            var itemId = el.attr(\"data-item-id\");\r\n" +
"            var price = parseFloat(costPrice || 0);\r\n\r\n            if (!price) {" +
"\r\n                alert(\"Cannot add item because the price is zero.\");\r\n        " +
"        return;\r\n            };\r\n\r\n\r\n\r\n            var targetEl = $(\"#OpeningIte" +
"ms\");\r\n            var selector = \"pos-\" + itemId;\r\n            var existingEl =" +
" $(\"#\" + selector);\r\n\r\n            if (existingEl.length) {\r\n                var" +
" existingQuantitySpan = existingEl.find(\"span.quantity\");\r\n                var e" +
"xistingQuantityInput = existingEl.find(\"input.quantity\");\r\n\r\n                var" +
" quantity = parseInt(existingQuantitySpan.text() || 0);\r\n                quantit" +
"y++;\r\n\r\n                existingQuantitySpan.text(quantity);\r\n                ex" +
"istingQuantityInput.val(quantity).trigger(\"keyup\");\r\n\r\n                window.up" +
"dateTotal();\r\n                return;\r\n            };\r\n\r\n            var templat" +
"e = itemTemplate;\r\n\r\n            template = template.replace(/{ItemId}/g, itemId" +
");\r\n            template = template.replace(/{CostPrice}/g, costPrice);\r\n       " +
"     template = template.replace(/{Photo}/g, photo);\r\n            template = tem" +
"plate.replace(/{BarCode}/g, barCode);\r\n            template = template.replace(/" +
"{BrandName}/g, brand);\r\n            template = template.replace(/{ItemGroupName}" +
"/g, itemGroup);\r\n            template = template.replace(/{ItemName}/g, itemName" +
");\r\n            template = template.replace(/{ItemCode}/g, itemCode);\r\n         " +
"   template = template.replace(/{Price}/g, price);\r\n            template = templ" +
"ate.replace(/{UnitId}/g, unitId);\r\n            template = template.replace(/{Val" +
"idUnits}/g, validUnits);\r\n\r\n            var item = $(template);\r\n            var" +
" quantityInput = item.find(\"input.quantity\");\r\n            var priceInput = item" +
".find(\"input.price\");\r\n            var unitSelect = item.find(\"select.unit\");\r\n\r" +
"\n            function loadUnits(el, defaultUnitId, validUnits) {\r\n              " +
"  el.html(\"\");\r\n\r\n                var units = window.Enumerable.From(window.meta" +
"Units)\r\n                    .Where(function (x) {\r\n                        retur" +
"n validUnits.indexOf(x.unit_id.toString()) > -1;\r\n                    }).ToArray" +
"();\r\n\r\n                $.each(units, function () {\r\n                    var unit" +
" = this;\r\n\r\n                    var option = $(\"<option/ >\");\r\n                 " +
"   option.attr(\"value\", unit.unit_id);\r\n                    option.html(unit.uni" +
"t_name);\r\n\r\n                    if (defaultUnitId === unit.unit_id) {\r\n         " +
"               option.attr(\"selected\", \"\");\r\n                    };\r\n\r\n         " +
"           option.appendTo(el);\r\n                });\r\n\r\n            };\r\n\r\n      " +
"      loadUnits(unitSelect, unitId, validUnits.split(\',\'));\r\n\r\n            funct" +
"ion updateItemTotal(el) {\r\n                var quantityEl = el.find(\"input.quant" +
"ity\");\r\n\r\n                var quantity = parseInt(quantityEl.val() || 0);\r\n     " +
"           var price = parseFloat(el.find(\"input.price\").val());\r\n              " +
"  //var price = parseFloat(el.attr(\"data-price\") || 0);\r\n\r\n                var a" +
"mount = (price * quantity).toFixed(2);\r\n\r\n                el.find(\"span.quantity" +
"\").html(quantity);\r\n                el.find(\"span.amount\").html(amount);\r\n\r\n    " +
"            window.updateTotal();\r\n\r\n            };\r\n\r\n            quantityInput" +
".on(\"keyup\", function () {\r\n                var el = $(this);\r\n                v" +
"ar parentInfo = el.parent().parent();\r\n                updateItemTotal(parentInf" +
"o);\r\n            });\r\n\r\n            priceInput.on(\"keyup\", function () {\r\n      " +
"          var el = $(this);\r\n                var parentInfo = el.parent().parent" +
"();\r\n                updateItemTotal(parentInfo);\r\n            });\r\n\r\n\r\n        " +
"    function getPrice(el) {\r\n                function request(itemId, unitId) {\r" +
"\n                    var url = \"/dashboard/inventory/items/cost-price/{itemId}/{" +
"unitId}\";\r\n                    url = url.replace(\"{itemId}\", itemId);\r\n         " +
"           url = url.replace(\"{unitId}\", unitId);\r\n\r\n                    return " +
"window.getAjaxRequest(url);\r\n                };\r\n\r\n                var itemId = " +
"el.attr(\"data-item-id\");\r\n                var unitId = el.val();\r\n\r\n            " +
"    $(\".pos.opening.segment\").addClass(\"loading\");\r\n                var ajax = r" +
"equest(itemId, unitId);\r\n\r\n                ajax.success(function (response) {\r\n " +
"                   $(\".pos.opening.segment\").removeClass(\"loading\");\r\n          " +
"          var priceInput = el.parent().parent().parent().find(\"input.price\");\r\n " +
"                   priceInput.val(response).trigger(\"keyup\");\r\n                }" +
");\r\n\r\n                ajax.fail(function (xr) {\r\n                    $(\".pos.ope" +
"ning.segment\").removeClass(\"loading\");\r\n                    console.log(window.g" +
"etAjaxErrorMessage(xhr));\r\n                });\r\n            };\r\n\r\n            un" +
"itSelect.on(\"change\", function () {\r\n                getPrice($(this));\r\n       " +
"     });\r\n\r\n            item.on(\"contextmenu\", function (e) {\r\n                e" +
".preventDefault();\r\n                var el = $(this);\r\n                var input" +
"El = el.find(\".number.block input\");\r\n                var buttonEl = el.find(\".n" +
"umber.block button\");\r\n\r\n                inputEl.toggle();\r\n                butt" +
"onEl.toggle();\r\n            });\r\n\r\n            item.appendTo(targetEl);\r\n       " +
"     quantityInput.trigger(\"keyup\");\r\n            window.updateTotal();\r\n       " +
" });\r\n    };\r\n\r\n    function updateTotal() {\r\n        var candidates = $(\"#Openi" +
"ngItems div.item\");\r\n        var amountEl = $(\"#SummaryItems div.amount .money\")" +
";\r\n\r\n        var totalPrice = 0;\r\n        //var totalQuantity = 0;\r\n\r\n        $." +
"each(candidates, function () {\r\n            var el = $(this);\r\n            var q" +
"uantityEl = el.find(\"input.quantity\");\r\n\r\n            var quantity = parseInt(qu" +
"antityEl.val() || 0);\r\n            var price = parseFloat(el.find(\"input.price\")" +
".val());\r\n            //var price = parseFloat(el.attr(\"data-price\") || 0);\r\n\r\n " +
"           var amount = price * quantity;\r\n            totalPrice += amount;\r\n  " +
"          //totalQuantity += quantity;\r\n        });\r\n\r\n        totalPrice = pars" +
"eFloat(totalPrice.toFixed(2));\r\n\r\n        amountEl.html(totalPrice);\r\n    };\r\n\r\n" +
"    function displayCategories() {\r\n        var categories = window.Enumerable.F" +
"rom(products).Distinct(function (x) { return x.ItemGroupName }).Select(function " +
"(x) { return x.ItemGroupName }).ToArray();\r\n        var targetEl = $(\".cat.filte" +
"r\");\r\n        $(\".category.list\").find(\".category\").remove();\r\n\r\n        targetE" +
"l.unbind(\"click\").bind(\"click\", function () {\r\n            displayProducts();\r\n " +
"           $(\".category\").removeClass(\"selected\");\r\n            targetEl.hide();" +
"\r\n            initializeClickAndAction();\r\n        });\r\n\r\n        $.each(categor" +
"ies, function () {\r\n            var category = $(\"<div class=\'category\' />\");\r\n " +
"           category.html(this);\r\n\r\n            category.unbind(\"click\").bind(\"cl" +
"ick\", function () {\r\n                $(\".search.panel input\").val(\"\");\r\n        " +
"        var el = $(this);\r\n                var name = el.text();\r\n\r\n            " +
"    if (name) {\r\n                    displayProducts(name);\r\n                   " +
" $(\".category\").removeClass(\"selected\");\r\n                    el.addClass(\"selec" +
"ted\");\r\n\r\n                    targetEl.show();\r\n                } else {\r\n      " +
"              targetEl.hide();\r\n                };\r\n\r\n                initialize" +
"ClickAndAction();\r\n            });\r\n\r\n            targetEl.before(category);\r\n  " +
"      });\r\n    };\r\n\r\n    function displayProducts(category, searchQuery) {\r\n    " +
"    var target = $(\"#POSItemList\");\r\n\r\n        var groupItems;\r\n\r\n        if (!c" +
"ategory && !searchQuery) {\r\n            groupItems = products;\r\n        } else {" +
"\r\n            if (category && searchQuery) {\r\n                groupItems = windo" +
"w.Enumerable\r\n                    .From(products)\r\n                    .Where(fu" +
"nction (x) {\r\n                        return x.ItemGroupName.toLowerCase() === c" +
"ategory.toString().toLowerCase()\r\n                            && x.ItemName.toLo" +
"werCase().indexOf(searchQuery.toLowerCase()) > -1;\r\n                    }).ToArr" +
"ay();\r\n            } else if (!category && searchQuery) {\r\n                group" +
"Items = window.Enumerable\r\n                    .From(products)\r\n                " +
"    .Where(function (x) {\r\n                        return x.ItemName.toLowerCase" +
"().indexOf(searchQuery.toLowerCase()) > -1;\r\n                    }).ToArray();\r\n" +
"            } else {\r\n                groupItems = window.Enumerable\r\n          " +
"          .From(products)\r\n                    .Where(function (x) {\r\n          " +
"              return x.ItemGroupName.toLowerCase() === category.toString().toLow" +
"erCase();\r\n                    }).ToArray();\r\n            };\r\n        };\r\n\r\n    " +
"    target.html(\"\").hide();\r\n\r\n        $.each(groupItems, function () {\r\n       " +
"     var product = this;\r\n\r\n            var item = $(\"<div class=\'item\' />\");\r\n " +
"           item.attr(\"data-item-id\", product.ItemId);\r\n            item.attr(\"da" +
"ta-item-code\", product.ItemCode);\r\n            item.attr(\"data-item-name\", produ" +
"ct.ItemName);\r\n            item.attr(\"data-item-group\", product.ItemGroupName);\r" +
"\n            item.attr(\"data-brand\", product.BrandName);\r\n            item.attr(" +
"\"data-unit-id\", product.UnitId);\r\n            item.attr(\"data-valid-units\", prod" +
"uct.ValidUnits);\r\n            item.attr(\"data-barcode\", product.Barcode);\r\n     " +
"       item.attr(\"data-photo\", product.Photo);\r\n            item.attr(\"data-cost" +
"-price\", product.CostPrice);\r\n\r\n            if (product.HotItem) {\r\n            " +
"    item.addClass(\"hot\");\r\n            };\r\n\r\n            var info = $(\"<div clas" +
"s=\'info\' />\");\r\n\r\n            var price = $(\"<div class=\'price\' />\");\r\n         " +
"   price.html(product.CostPrice);\r\n\r\n            price.appendTo(info);\r\n\r\n\r\n    " +
"        var photo = $(\"<div class=\'photo\' />\");\r\n            var img = $(\"<img /" +
">\");\r\n            img.attr(\"src\", product.Photo + \"?Height=200&Width=200\");\r\n\r\n " +
"           img.appendTo(photo);\r\n            photo.appendTo(info);\r\n\r\n          " +
"  var name = $(\"<div class=\'name\' />\");\r\n            name.html(product.ItemName)" +
";\r\n\r\n            name.appendTo(info);\r\n\r\n            info.appendTo(item);\r\n     " +
"       item.appendTo(target);\r\n        });\r\n\r\n        if (searchQuery) {\r\n      " +
"      target.show();\r\n            return;\r\n        };\r\n\r\n        target.fadeIn(5" +
"00);\r\n    };\r\n\r\n    </script>\r\n");

WriteLiteral("    <script>\r\n    $(\"#CheckoutButton\").unbind(\"click\").bind(\"click\", function () " +
"{\r\n\r\n        function request(model) {\r\n            var url = \"/dashboard/invent" +
"ory/setup/opening-inventory/new\";\r\n            var data = JSON.stringify(model);" +
"\r\n            return window.getAjaxRequest(url, \"POST\", data);\r\n        };\r\n\r\n  " +
"      function getModel() {\r\n            function getDetails() {\r\n              " +
"  var items = $(\"#OpeningItems .item\");\r\n                var model = [];\r\n\r\n    " +
"            $.each(items, function () {\r\n                    var el = $(this);\r\n" +
"                    var itemId = parseInt(el.attr(\"data-item-id\"));\r\n           " +
"         var quantity = parseInt(el.find(\"input.quantity\").val());\r\n            " +
"        var unitId = parseInt(el.find(\"select.unit\").val());\r\n                  " +
"  var price = parseFloat(el.find(\"input.price\").val() || 0);\r\n\r\n                " +
"    model.push({\r\n                        StoreId: $(\"#StoreSelect\").val(),\r\n   " +
"                     ItemId: itemId,\r\n                        Quantity: quantity" +
",\r\n                        UnitId: unitId,\r\n                        Price: price" +
"\r\n                    });\r\n                });\r\n\r\n                return model;\r" +
"\n            };\r\n\r\n            var valueDate = $(\"#ValueDateInputDate\").datepick" +
"er(\"getDate\");\r\n            var bookDate = $(\"#BookDateInputDate\").datepicker(\"g" +
"etDate\");\r\n            var referenceNumber = $(\"#ReferenceNumberInputText\").val(" +
");\r\n            var statementReference = $(\"#StatementReferenceInputText\").val()" +
";\r\n            var storeId = $(\"#StoreSelect\").val();\r\n            var details =" +
" getDetails();\r\n\r\n            return {\r\n                ValueDate: valueDate,\r\n " +
"               BookDate: bookDate,\r\n                ReferenceNumber: referenceNu" +
"mber,\r\n                StatementReference: statementReference,\r\n                " +
"Details: details\r\n            };\r\n        };\r\n\r\n        var model = getModel();\r" +
"\n\r\n        if (!model.Details.length) {\r\n            window.displayMessage(\"Plea" +
"se select an item.\");\r\n            return;\r\n        };\r\n\r\n        var confirmed " +
"= confirm(\"Are you sure\");\r\n\r\n        if (!confirmed) {\r\n            return;\r\n  " +
"      };\r\n\r\n\r\n        $(\"#CheckoutButton\").addClass(\"loading\");\r\n\r\n        var a" +
"jax = request(model);\r\n\r\n        ajax.success(function (response) {\r\n           " +
" var id = response;\r\n            document.location = \"/dashboard/inventory/setup" +
"/opening-inventory/checklist/\" + id;\r\n        });\r\n\r\n        ajax.fail(function " +
"(xhr) {\r\n            $(\"#CheckoutButton\").removeClass(\"loading\");\r\n            a" +
"lert(JSON.stringify(xhr));\r\n        });\r\n    });\r\n    </script>\r\n");

            
            #line 1040 "..\..\Views\Setup\OpeningInventory\New.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"    <script>
    $(""#ClearScreenButton"")
        .unbind(""click"")
        .bind(""click"",
            function () {
                clearScreen();
            });

    function clearScreen() {
        $(""#OpeningItems"").html("""");
        window.updateTotal();
    };
    </script>
");

            
            #line 1054 "..\..\Views\Setup\OpeningInventory\New.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"    <script>
    function displayFieldBinder(el, url) {
        function request() {
            return window.getAjaxRequest(url);
        };

        var ajax = request();

        ajax.success(function (response) {
            var options = """";

            $.each(response, function () {
                var option = ""<option value='{key}'>{value}</option>"";
                option = option.replace(""{key}"", this.Key);
                option = option.replace(""{value}"", this.Value);

                options += option;
            });

            el.html(options);
        });
    };

    function loadStores() {
        displayFieldBinder($(""#StoreSelect""), ""/api/forms/inventory/stores/display-fields"");
    };

    loadStores();
    </script>
");

            
            #line 1084 "..\..\Views\Setup\OpeningInventory\New.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n    setTimeout(function () {\r\n        $(\".decimal\").number(true, wi" +
"ndow.currencyDecimalPlaces, \".\", \"\");\r\n    }, 100);\r\n\r\n    window.overridePath =" +
" \"/dashboard/inventory/setup/opening-inventory\";\r\n    </script>\r\n");

            
            #line 1092 "..\..\Views\Setup\OpeningInventory\New.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
