#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.Inventory;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/Customers.cshtml")]
    public partial class _Views_Setup_Customers_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_Customers_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\Customers.cshtml"
  
    ViewBag.Title = "Customers";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"C" +
"ustomers\";\r\n\r\n    scrudFactory.viewAPI = \"/api/forms/inventory/customers\";\r\n    " +
"scrudFactory.viewTableName = \"inventory.customers\";\r\n\r\n    scrudFactory.formAPI " +
"= \"/api/forms/inventory/customers\";\r\n    scrudFactory.formTableName = \"inventory" +
".customers\";\r\n\r\n    scrudFactory.uploadHanlder = \"/dashboard/inventory/services/" +
"attachments\";\r\n\r\n    scrudFactory.excludedColumns = [\"audit_user_id\", \"audit_ts\"" +
"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFactory.allowEdit = true;\r\n" +
"\r\n    scrudFactory.live = \"CustomerName\";\r\n\r\n    scrudFactory.card = {\r\n        " +
"image: \"Photo\",\r\n        header: \"CustomerName\",\r\n        meta: \"CustomerCode\",\r" +
"\n        description: \"ContactPhoneNumbers\"        \r\n    };\r\n\r\n    scrudFactory." +
"layout = [\r\n        {\r\n            tab: \"\",\r\n            fields: [\r\n            " +
"    [\"CustomerId\", \"\"],\r\n                [\"Photo\", \"\"],\r\n                [\"Custo" +
"merCode\", \"CustomerName\"],\r\n                [\"CustomerTypeId\", \"\"],\r\n           " +
"     [\"Logo\", \"\"]\r\n            ]\r\n        }\r\n    ];\r\n\r\n    scrudFactory.keys = [" +
"\r\n        {\r\n            property: \"CustomerTypeId\",\r\n            url: \'/api/for" +
"ms/inventory/customer-types/display-fields\',\r\n            data: null,\r\n         " +
"   valueField: \"Key\",\r\n            textField: \"Value\"\r\n        },\r\n        {\r\n  " +
"          property: \"AccountId\",\r\n            url: \'/api/views/finance/receivabl" +
"e-account-selector-view/display-fields\',\r\n            data: null,\r\n            v" +
"alueField: \"Key\",\r\n            textField: \"Value\"\r\n        },\r\n        {\r\n      " +
"      property: \"CurrencyCode\",\r\n            url: \'/api/views/core/currencies/di" +
"splay-fields\',\r\n            data: null,\r\n            valueField: \"Key\",\r\n       " +
"     textField: \"Value\"\r\n        }\r\n    ];\r\n\r\n\r\n\r\n    $.get(\'/ScrudFactory/View." +
"html\', function (view) {\r\n        $.get(\'/ScrudFactory/Form.html\', function (for" +
"m) {\r\n            $(\"#ScrudFactoryView\").html(view);\r\n            $(\"#ScrudFacto" +
"ryForm\").html(form);\r\n            $.cachedScript(\"/assets/js/scrudfactory-view.j" +
"s\");\r\n            $.cachedScript(\"/assets/js/scrudfactory-form.js\");\r\n        })" +
";\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
