#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Inventory;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/ItemTypes.cshtml")]
    public partial class _Views_Setup_ItemTypes_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_ItemTypes_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\ItemTypes.cshtml"
  
    ViewBag.Title = "Item Types";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"I" +
"tem Types\";\r\n\r\n    scrudFactory.viewAPI = \"/api/forms/inventory/item-types\";\r\n  " +
"  scrudFactory.viewTableName = \"inventory.item_types\";\r\n\r\n    scrudFactory.formA" +
"PI = \"/api/forms/inventory/item-types\";\r\n    scrudFactory.formTableName = \"inven" +
"tory.item_types\";\r\n\r\n    scrudFactory.excludedColumns = [\"audit_user_id\", \"audit" +
"_ts\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFactory.allowEdit = tru" +
"e;\r\n\r\n    scrudFactory.live = \"ItemTypeName\";\r\n\r\n    scrudFactory.card = {\r\n    " +
"    header: \"item_type_name\",\r\n        meta: \"item_type_code\",\r\n        descript" +
"ion: \"is_component\"\r\n    };\r\n\r\n    //scrudFactory.layout = [\r\n    //    {\r\n    /" +
"/        tab: \"\",\r\n    //        fields: [\r\n    //            [\"\", \"\"],\r\n    // " +
"           [\"\", \"\"],\r\n    //        ]\r\n    //    }\r\n    //];\r\n\r\n    //scrudFacto" +
"ry.keys = [\r\n    //    {\r\n    //        property: \"CamelCase\",\r\n    //        ur" +
"l: \'/api/forms/schema/table/display-fields\',\r\n    //        data: null,\r\n    // " +
"       valueField: \"Key\",\r\n    //        textField: \"Value\"\r\n    //    }\r\n    //" +
"];\r\n\r\n\r\n\r\n    $.get(\'/ScrudFactory/View.html\', function (view) {\r\n        $.get(" +
"\'/ScrudFactory/Form.html\', function (form) {\r\n            $(\"#ScrudFactoryView\")" +
".html(view);\r\n            $(\"#ScrudFactoryForm\").html(form);\r\n            $.cach" +
"edScript(\"/assets/js/scrudfactory-view.js\");\r\n            $.cachedScript(\"/asset" +
"s/js/scrudfactory-form.js\");\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
