-->-->-- src/Frapid.Web/Areas/MixERP.Inventory/db/SQL Server/2.x/2.0/src/99.sample-data/inventory.sample.sql --<--<--
INSERT INTO inventory.brands(brand_code, brand_name)
SELECT 'DEF', 'Default';

INSERT INTO inventory.units(unit_code, unit_name)
SELECT 'PC', 'Piece'        UNION ALL
SELECT 'FT', 'Feet'         UNION ALL
SELECT 'MTR', 'Meter'       UNION ALL
SELECT 'LTR', 'Liter'       UNION ALL
SELECT 'GM', 'Gram'         UNION ALL
SELECT 'KG', 'Kilogram'     UNION ALL
SELECT 'DZ', 'Dozen'        UNION ALL
SELECT 'BX', 'Box';


INSERT INTO inventory.compound_units(base_unit_id, compare_unit_id, value)
SELECT inventory.get_unit_id_by_unit_code('PC'), inventory.get_unit_id_by_unit_code('DZ'), 12     UNION ALL
SELECT inventory.get_unit_id_by_unit_code('DZ'), inventory.get_unit_id_by_unit_code('BX'), 100    UNION ALL
SELECT inventory.get_unit_id_by_unit_code('GM'), inventory.get_unit_id_by_unit_code('KG'), 1000;

INSERT INTO inventory.brands(brand_code, brand_name)
SELECT 'COK', 'Coke'        UNION ALL
SELECT 'FAN', 'Fanta'        UNION ALL
SELECT 'BMB', 'Bambino'     UNION ALL
SELECT 'BRG', 'Broges'      UNION ALL
SELECT 'DIL', 'Dilmah'      UNION ALL
SELECT 'NST', 'Nestle'      UNION ALL
SELECT 'DDC', 'DDC'          UNION ALL
SELECT 'DBR', 'Dabur'          UNION ALL
SELECT 'BTN', 'Britannia'   UNION ALL
SELECT 'GAI', 'GAIA'          UNION ALL
SELECT 'MCH', 'Munchys'     UNION ALL
SELECT 'AML', 'Amul';

INSERT INTO inventory.item_types(item_type_code, item_type_name, is_component)
SELECT 'GEN', 'General',        0      UNION ALL
SELECT 'COM', 'Component',      1       UNION ALL
SELECT 'MAF', 'Manufacturing',  0;

INSERT INTO inventory.customer_types(customer_type_code, customer_type_name, account_id) 
SELECT 'A', 'Agent', finance.get_account_id_by_account_number('20100') UNION ALL
SELECT 'C', 'Customer', finance.get_account_id_by_account_number('10400');

INSERT INTO inventory.supplier_types(supplier_type_code, supplier_type_name, account_id) 
SELECT 'S', 'Supplier', finance.get_account_id_by_account_number('20100');

INSERT INTO inventory.suppliers(supplier_code, supplier_name, supplier_type_id, company_name, account_id, currency_code)
SELECT 'DEF', 'Default', inventory.get_supplier_type_id_by_supplier_type_code('S'),           'Default',            finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'COK', 'Coke', inventory.get_supplier_type_id_by_supplier_type_code('S'),               'Coke',                finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'FAN', 'Fanta', inventory.get_supplier_type_id_by_supplier_type_code('S'),             'Fanta',              finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'BMB', 'Bambino', inventory.get_supplier_type_id_by_supplier_type_code('S'),            'Bambino',             finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'BRG', 'Broges', inventory.get_supplier_type_id_by_supplier_type_code('S'),            'Broges',             finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'DIL', 'Dilmah', inventory.get_supplier_type_id_by_supplier_type_code('S'),             'Dilmah',              finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'NST', 'Nestle', inventory.get_supplier_type_id_by_supplier_type_code('S'),          'Nestle',           finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'DDC', 'DDC', inventory.get_supplier_type_id_by_supplier_type_code('S'),               'DDC',                finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'DBR', 'Dabur', inventory.get_supplier_type_id_by_supplier_type_code('S'),           'Dabur',            finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'BTN', 'Britannia', inventory.get_supplier_type_id_by_supplier_type_code('S'),         'Britannia',          finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'GAI', 'GAIA', inventory.get_supplier_type_id_by_supplier_type_code('S'),            'GAIA',             finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'MCH', 'Munchys', inventory.get_supplier_type_id_by_supplier_type_code('S'),         'Munchys',          finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'AML', 'Amul', inventory.get_supplier_type_id_by_supplier_type_code('S'),             'Amul',              finance.get_account_id_by_account_number('20100'), 'USD';


INSERT INTO inventory.shippers(shipper_name, company_name, account_id)
SELECT 'Default', 'Default', finance.get_account_id_by_account_number('20110');


INSERT INTO inventory.item_groups(item_group_code, item_group_name, sales_account_id, sales_discount_account_id, sales_return_account_id, purchase_account_id, purchase_discount_account_id, inventory_account_id, cost_of_goods_sold_account_id)
SELECT 'DEF', 'Default', finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200');


INSERT INTO inventory.item_groups(item_group_code, item_group_name, parent_item_group_id, sales_account_id, sales_discount_account_id, sales_return_account_id, purchase_account_id, purchase_discount_account_id, inventory_account_id, cost_of_goods_sold_account_id)
SELECT 'FSTF',     'Fast Food',                           CAST(NULL AS integer),    finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200')    UNION ALL
SELECT 'SOF',     'Soft Drinks',                       NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200')    UNION ALL
SELECT 'DRF',     'Dry Foods',                           NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'NAP',     'Noodles & pastas',                 NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'TCHD',     'Tea,Coffee & Health Drinks',        NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'DP',     'Dairy Products',                    NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'HN',     'Honey',                            NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'BCTS',     'Biscuits',                            NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'FRF',     'Frozen Foods',                        NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'FRUI',     'Fruits',                            NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'VEBL',     'Vegitables',                        NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200') UNION ALL    
SELECT 'CHLS',     'Chocolates',                        NULL,            finance.get_account_id_by_account_number('30100'), finance.get_account_id_by_account_number('40270'), finance.get_account_id_by_account_number('20701'), finance.get_account_id_by_account_number('40100'), finance.get_account_id_by_account_number('30700'), finance.get_account_id_by_account_number('10700'), finance.get_account_id_by_account_number('40200');    


INSERT INTO inventory.store_types(store_type_code,store_type_name)
SELECT 'GD', 'Godown'                              UNION ALL
SELECT 'SAL', 'Sales Center'                        UNION ALL
SELECT 'WAR', 'Warehouse'                           UNION ALL
SELECT 'PRO', 'Production';



INSERT INTO inventory.stores(office_id, store_code, store_name, city, store_type_id, allow_sales, default_cash_account_id, default_cash_repository_id, default_account_id_for_checks)
SELECT 1, 'STORE-1', 'Store 1',     'Office', inventory.get_store_type_id_by_store_type_code('SAL'), 1, finance.get_account_id_by_account_number('10200'), finance.get_cash_repository_id_by_cash_repository_code('CAC'), finance.get_account_id_by_account_number('10500')    UNION ALL
SELECT 1, 'GODOW-1', 'Godown 1',    'Office', inventory.get_store_type_id_by_store_type_code('GD'), 0, finance.get_account_id_by_account_number('10200'), finance.get_cash_repository_id_by_cash_repository_code('CAC'), finance.get_account_id_by_account_number('10500')   UNION ALL
SELECT 1, 'STORE-2', 'Store 2',     'Office', inventory.get_store_type_id_by_store_type_code('SAL'), 1, finance.get_account_id_by_account_number('10200'), finance.get_cash_repository_id_by_cash_repository_code('CAC'), finance.get_account_id_by_account_number('10500')    UNION ALL
SELECT 1, 'GODOW-2', 'Godown 2',    'Office', inventory.get_store_type_id_by_store_type_code('GD'), 0, finance.get_account_id_by_account_number('10200'), finance.get_cash_repository_id_by_cash_repository_code('CAC'), finance.get_account_id_by_account_number('10500')   UNION ALL
SELECT 1, 'STORE-3', 'Store 3',     'Office', inventory.get_store_type_id_by_store_type_code('SAL'), 1, finance.get_account_id_by_account_number('10200'), finance.get_cash_repository_id_by_cash_repository_code('CAC'), finance.get_account_id_by_account_number('10500')    UNION ALL
SELECT 1, 'GODOW-3', 'Godown 3',    'Office', inventory.get_store_type_id_by_store_type_code('GD'), 0, finance.get_account_id_by_account_number('10200'), finance.get_cash_repository_id_by_cash_repository_code('CAC'), finance.get_account_id_by_account_number('10500');

INSERT INTO inventory.counters(counter_code, counter_name, store_id)
SELECT 'COU-1', 'Counter 1', inventory.get_store_id_by_store_code('STORE-1') UNION ALL
SELECT 'COU-2', 'Counter 2', inventory.get_store_id_by_store_code('STORE-2') UNION ALL
SELECT 'COU-3', 'Counter 3', inventory.get_store_id_by_store_code('STORE-3');

INSERT INTO inventory.items(item_code, item_name, item_group_id, item_type_id, brand_id, preferred_supplier_id, unit_id, hot_item, reorder_level, maintain_inventory, cost_price, selling_price, reorder_unit_id, reorder_quantity)
SELECT 'SMOMO', 'Steamed MOMO',                             inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    80,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BRYN',  'Briyani',                                     inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    150,   2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'PZZA',  'Pizza',                                    inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    200,   2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'SAWH',  'Sandwich',                                  inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    150,   2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'HMBR',  'Hamburger',                                 inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    80,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CLSW',  'Club Sandwich',                              inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'SAMS',  'Samosa',                                     inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    20    ,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CHWN',  'Chowmein',                                  inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    50,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'FHFS',  'French Fries',                             inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    50,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'OMLT',  'Omlet',                                    inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    50,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'FHFY',  'Fish Fry',                                  inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    80,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'EGSP',  'Egg Soup',                                 inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    95,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CKSP',  'Chicken Soup',                              inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'TTSP',  'Tomato Soup',                              inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    100,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'MTBL',  'Meat Ball',                                  inventory.get_item_group_id_by_item_group_code('FSTF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'COK',      'Coca Cola',                                 inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('COK'),       inventory.get_supplier_id_by_supplier_code('COK'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    80,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DCOK',  'Diet Coke',                                inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('COK'),       inventory.get_supplier_id_by_supplier_code('COK'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    90,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'RMTE',  'Romanette',                                inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    150,   2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'PEPS',  'Pepsi',                                    inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    50,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'LMJC',  'Lemon Juice',                                inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    50,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'SOD',      'Soda',                                      inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    100,    1,    70,    2250, inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'FNT',      'Fanta',                                     inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('FAN'),       inventory.get_supplier_id_by_supplier_code('FAN'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    50,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'PCJC',  'Panchy Juice',                              inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    90,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BNTG',  'Bintang',                                     inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    150,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'RDB',      'Red Bull',                                  inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    50,    50,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'SPT',      'Sprite',                                    inventory.get_item_group_id_by_item_group_code('SOF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    50,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'ALM',      'Almond',                                    inventory.get_item_group_id_by_item_group_code('DRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'ASC',      'American Sweet Corn',                       inventory.get_item_group_id_by_item_group_code('DRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    100,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CSW',      'Cashew Nuts',                               inventory.get_item_group_id_by_item_group_code('DRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    500,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DRF',      'Dry Fruits',                                inventory.get_item_group_id_by_item_group_code('DRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'PST',      'Pista',                                     inventory.get_item_group_id_by_item_group_code('DRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'RSN',      'Raisin',                                    inventory.get_item_group_id_by_item_group_code('DRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'WLN',      'Wallnut',                                   inventory.get_item_group_id_by_item_group_code('DRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BRST',  'Brownie Sweets',                            inventory.get_item_group_id_by_item_group_code('CHLS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'TWIX',    'Twix',                                        inventory.get_item_group_id_by_item_group_code('CHLS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    80,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'SWBL',  'Sweet Balls',                                inventory.get_item_group_id_by_item_group_code('CHLS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    50,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DBMC',  'Dark Drown Milk Candy',                      inventory.get_item_group_id_by_item_group_code('CHLS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    100,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'SNKR',  'Snickers',                                  inventory.get_item_group_id_by_item_group_code('CHLS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    120,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'ICCB',  'Ice Cubes',                                   inventory.get_item_group_id_by_item_group_code('CHLS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    80,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CHBR',  'Chocolate Bars',                           inventory.get_item_group_id_by_item_group_code('CHLS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    30,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'NIBB',  'Nibble',                                   inventory.get_item_group_id_by_item_group_code('CHLS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    90,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'AGBT',     'Agnesi Bucatini',                            inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    100,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BMP',      'Bambino Macaroni PEP',                       inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('BMB'),       inventory.get_supplier_id_by_supplier_code('BMB'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    80,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BPP',      'Bambino Premium Pasta',                       inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('BMB'),       inventory.get_supplier_id_by_supplier_code('BMB'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    200,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BFP',      'Borges Fusilli Pasta',                        inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('BRG'),       inventory.get_supplier_id_by_supplier_code('BRG'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BPRP',  'Borges Penne Rigate Pasta',                inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('BRG'),       inventory.get_supplier_id_by_supplier_code('BRG'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    200,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BS',      'Borges Spaghetti',                            inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('BRG'),       inventory.get_supplier_id_by_supplier_code('BRG'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    180,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DP',      'Divellaa Pasta',                              inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'LS',      'Licco Spaghetti',                           inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    180,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'WAI',   'Wai Wai',                                   inventory.get_item_group_id_by_item_group_code('NAP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    20,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DACT',  'Dilmah Default Ceylon Tea',                inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DIL'),       inventory.get_supplier_id_by_supplier_code('DIL'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DCAC',  'Dilmah Cherry & Almond Ceylon Tea',           inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DIL'),       inventory.get_supplier_id_by_supplier_code('DIL'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DGT',      'Dilmah Green Tea',                           inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DIL'),       inventory.get_supplier_id_by_supplier_code('DIL'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DGTJ',  'Dilmah Green Tea Jasmine',                    inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DIL'),       inventory.get_supplier_id_by_supplier_code('DIL'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DLCT',  'Dilmah Lemon Ceylon Tea',                    inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DIL'),       inventory.get_supplier_id_by_supplier_code('DIL'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    200,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'MSTE',  'Masala Tea',                                inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CM',      'Coffee Mate',                              inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CPGFC', 'Cafe Pele ld Freeze Coffee',               inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BLEN',     'Black Energy',                             inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'RLMS',  'Relemless',                                  inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'XS',      'XS Energy Drink',                           inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    200,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'LVED',  'Las Vegas Energy Drink',                   inventory.get_item_group_id_by_item_group_code('TCHD'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'ABT',      'Amul Butter',                                inventory.get_item_group_id_by_item_group_code('DP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('AML'),       inventory.get_supplier_id_by_supplier_code('AML'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    200,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DYC',      'DDC Yak Cheese',                           inventory.get_item_group_id_by_item_group_code('DP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DDC'),       inventory.get_supplier_id_by_supplier_code('DDC'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'NEDW',     'Nestle EveryDay Dairy Whitener',           inventory.get_item_group_id_by_item_group_code('DP'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('NST'),       inventory.get_supplier_id_by_supplier_code('NST'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DHON',     'Dabur Honey',                               inventory.get_item_group_id_by_item_group_code('HN'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DBR'),       inventory.get_supplier_id_by_supplier_code('DBR'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    500,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'DAHE',     'Dark Honey',                               inventory.get_item_group_id_by_item_group_code('HN'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DBR'),       inventory.get_supplier_id_by_supplier_code('DBR'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    500,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BGDC',  'Britannia od Day Cashew Cookies',        inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('BTN'),       inventory.get_supplier_id_by_supplier_code('BTN'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    200,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BGDP',  'Britannia od Day Pistachio Cookies',     inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('BTN'),       inventory.get_supplier_id_by_supplier_code('BTN'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'GLSF',     'GAIA Lite Sugar Free Bites',               inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('GAI'),       inventory.get_supplier_id_by_supplier_code('GAI'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'GLOC',     'GAIA Oatmeal Cookies',                     inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('GAI'),       inventory.get_supplier_id_by_supplier_code('GAI'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    180,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'MVDL',  'McVities Digestive Light',                 inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'MUCS',  'Munchys Cracker Sandwich',                   inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('MCH'),       inventory.get_supplier_id_by_supplier_code('MCH'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'MUCC',  'Munchys Cream Crackers',                   inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('MCH'),       inventory.get_supplier_id_by_supplier_code('MCH'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'MUSC',  'Munchys Sugar Crackers',                   inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('MCH'),       inventory.get_supplier_id_by_supplier_code('MCH'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'MUVC',  'Munchys Vege Crackers',                    inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('MCH'),       inventory.get_supplier_id_by_supplier_code('MCH'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'TFDN',  'Tiffany Digestive Natural',                inventory.get_item_group_id_by_item_group_code('BCTS'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'RSBR',  'Raspberry',                                inventory.get_item_group_id_by_item_group_code('FRUI'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    80,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BNAN',  'Banana',                                     inventory.get_item_group_id_by_item_group_code('FRUI'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    70,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'ORGS',     'Orange',                                   inventory.get_item_group_id_by_item_group_code('FRUI'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    60,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'GRPS',     'Grapes',                                     inventory.get_item_group_id_by_item_group_code('FRUI'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    75,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'STBR',  'Straberries',                                 inventory.get_item_group_id_by_item_group_code('FRUI'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'APPL',  'Default',                                   inventory.get_item_group_id_by_item_group_code('FRUI'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'WAME',  'Water Melon',                               inventory.get_item_group_id_by_item_group_code('FRUI'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    120,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'PIAP',  'Pine Default',                               inventory.get_item_group_id_by_item_group_code('FRUI'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'TMTO',  'Tomato',                                    inventory.get_item_group_id_by_item_group_code('VEBL'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    80,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'PTTO',  'Potatos',                                     inventory.get_item_group_id_by_item_group_code('VEBL'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    200,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'ONNS',     'Onions',                                   inventory.get_item_group_id_by_item_group_code('VEBL'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BRJL',     'Brinjal',                                     inventory.get_item_group_id_by_item_group_code('VEBL'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    50,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'PMPS',  'Pumpkins',                                 inventory.get_item_group_id_by_item_group_code('VEBL'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    80,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'RDCL',  'Red Chili',                                   inventory.get_item_group_id_by_item_group_code('VEBL'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    30,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CARR',  'Carrot',                                   inventory.get_item_group_id_by_item_group_code('VEBL'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    100,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'SPCH',  'Spinach',                                   inventory.get_item_group_id_by_item_group_code('VEBL'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    20,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BCN',   'Bacon',                                    inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BDRM',  'Buff Dry Meat',                             inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    180,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'BFSG',     'Buff Sausage',                               inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    80,    450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CBLB',     'Chicken Boneless Breast',                     inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    250,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CHDS',  'Chicken Drumstick',                         inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CHLL',  'Chicken Lolly',                               inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    350,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'MUCB',  'Mutton Cubes',                               inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    400,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'POBL',  'Pork Belly',                               inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    500,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'PORB',  'Pork Ribs',                                inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    300,   450,  inventory.get_unit_id_by_unit_code('PC'), 200  UNION ALL
SELECT 'CHLV',  'Chicken Liver',                            inventory.get_item_group_id_by_item_group_code('FRF'),    inventory.get_item_type_id_by_item_type_code('GEN'), inventory.get_brand_id_by_brand_code('DEF'),       inventory.get_supplier_id_by_supplier_code('DEF'),  inventory.get_unit_id_by_unit_code('PC'), 0,    10,     1,    150,   450,  inventory.get_unit_id_by_unit_code('PC'), 200;


UPDATE inventory.items
SET photo = '/dashboard/inventory/services/attachments/' + item_code + '.jpg'
WHERE inventory.items.maintain_inventory = 1;


INSERT INTO inventory.customers(customer_code, customer_name, customer_type_id, company_name, account_id, currency_code)
SELECT 'DEF', 'Default', inventory.get_customer_type_id_by_customer_type_code('C'),           'Default',            finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'COK', 'Coke', inventory.get_customer_type_id_by_customer_type_code('C'),               'Coke',                finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'FAN', 'Fanta', inventory.get_customer_type_id_by_customer_type_code('C'),             'Fanta',              finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'BMB', 'Bambino', inventory.get_customer_type_id_by_customer_type_code('C'),            'Bambino',             finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'BRG', 'Broges', inventory.get_customer_type_id_by_customer_type_code('C'),            'Broges',             finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'DIL', 'Dilmah', inventory.get_customer_type_id_by_customer_type_code('C'),             'Dilmah',              finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'NST', 'Nestle', inventory.get_customer_type_id_by_customer_type_code('C'),          'Nestle',           finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'DDC', 'DDC', inventory.get_customer_type_id_by_customer_type_code('C'),               'DDC',                finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'DBR', 'Dabur', inventory.get_customer_type_id_by_customer_type_code('C'),           'Dabur',            finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'BTN', 'Britannia', inventory.get_customer_type_id_by_customer_type_code('C'),         'Britannia',          finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'GAI', 'GAIA', inventory.get_customer_type_id_by_customer_type_code('C'),            'GAIA',             finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'MCH', 'Munchys', inventory.get_customer_type_id_by_customer_type_code('C'),            'Munchys',             finance.get_account_id_by_account_number('20100'), 'USD' UNION ALL
SELECT 'AML', 'Amul', inventory.get_customer_type_id_by_customer_type_code('C'),             'Dilmah',              finance.get_account_id_by_account_number('20100'), 'USD';

--ROLLBACK TRANSACTION;

UPDATE inventory.items
SET cost_price = ROUND(cost_price / 100, 2),
selling_price = ROUND(cost_price / 70, 2);

GO

