#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Inventory;
    
    #line 1 "..\..\Views\Tasks\Adjustment\Checklist.cshtml"
    using MixERP.Inventory.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Adjustment/Checklist.cshtml")]
    public partial class _Views_Tasks_Adjustment_Checklist_cshtml : System.Web.Mvc.WebViewPage<long>
    {
        public _Views_Tasks_Adjustment_Checklist_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Adjustment\Checklist.cshtml"
  
    ViewBag.Title = "Checklist";
    Layout = ViewBag.InventoryLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Tasks\Adjustment\Checklist.cshtml"
Write(Html.FinancePartialView("Shared/Checklist.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    window.overridePath = \"/dashboard/inventory/tasks/inventory-tra" +
"nsfers\";\r\n\r\n    window.prepareChecklist({\r\n        Title: \"Inventory Adjustment " +
"Checklist #");

            
            #line 14 "..\..\Views\Tasks\Adjustment\Checklist.cshtml"
                                           Write(Model);

            
            #line default
            #line hidden
WriteLiteral(@""",
        ViewText: ""View Adjustments"",
        ViewUrl: ""/dashboard/inventory/tasks/inventory-adjustments"",
        AddNewText: ""Add New Adjustment"",
        AddNewUrl: ""/dashboard/inventory/tasks/inventory-adjustments/new"",
        ReportPath: ""/dashboard/reports/source/Areas/MixERP.Inventory/Reports/Adjustment.xml?transaction_master_id=");

            
            #line 19 "..\..\Views\Tasks\Adjustment\Checklist.cshtml"
                                                                                                              Write(Model);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
