#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Tasks\Adjustment\Index.cshtml"
    using Frapid.ApplicationState.Cache;
    
    #line default
    #line hidden
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Inventory;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Adjustment/Index.cshtml")]
    public partial class _Views_Tasks_Adjustment_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Adjustment_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Adjustment\Index.cshtml"
  
    ViewBag.Title = "Inventory Adjustment";
    Layout = ViewBag.InventoryLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .modal iframe {\r\n        width: 100%;\r\n        border: none;\r\n    " +
"    height: 700px;\r\n    }\r\n</style>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<div");

WriteLiteral(" class=\"ui attached segment\"");

WriteLiteral(" style=\"min-height: 100%; padding: 3em;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Inventory Adjustments</div>\r\n        <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"ui stackable grid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"twelve wide column\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui basic buttons\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" id=\"AddNewButton\"");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(" style=\"\"");

WriteLiteral(" href=\"/dashboard/inventory/tasks/inventory-adjustments/new\"");

WriteLiteral(">\r\n                        Add New\r\n                    </a>\r\n                   " +
" <div");

WriteLiteral(" class=\"ui icon top left pointing dropdown basic button\"");

WriteLiteral(" id=\"ExportDropDown\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">\r\n                        <span>\r\n                            Export\r\n          " +
"              </span>\r\n                        <div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n                                Export This Document\r\n                        " +
"    </div>\r\n                            <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createDoc();\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"file word outline blue icon\"");

WriteLiteral("></i> Export to Doc\r\n                            </a>\r\n                          " +
"  <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createXls();\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"file excel outline green icon\"");

WriteLiteral("></i> Export to Excel\r\n                            </a>\r\n                        " +
"    <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createPDF();\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"file pdf outline red icon\"");

WriteLiteral("></i> Export to PDF\r\n                            </a>\r\n                        </" +
"div>\r\n                    </div>\r\n                    <a");

WriteLiteral(" id=\"PrintButton\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"print()\"");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">\r\n                        Print\r\n                    </a>\r\n                </div" +
">\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui stackable form query segment\"");

WriteLiteral(" id=\"Annotation\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"twelve fields\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"date\"");

WriteLiteral(" data-persist");

WriteLiteral(" placeholder=\"DateFrom\"");

WriteLiteral(" id=\"FromInputText\"");

WriteLiteral(" title=\"DateFrom\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"date\"");

WriteLiteral(" data-persist");

WriteLiteral(" placeholder=\"DateTo\"");

WriteLiteral(" id=\"ToInputText\"");

WriteLiteral(" title=\"DateTo\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" placeholder=\"TranId\"");

WriteLiteral(" id=\"TranIdInputText\"");

WriteLiteral(" title=\"TranId\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" placeholder=\"TranCode\"");

WriteLiteral(" id=\"TranCodeInputText\"");

WriteLiteral(" title=\"TranCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" placeholder=\"Office\"");

WriteLiteral(" id=\"OfficeInputText\"");

WriteLiteral(" title=\"Office\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" placeholder=\"ReferenceNumber\"");

WriteLiteral(" id=\"ReferenceNumberInputText\"");

WriteLiteral(" title=\"ReferenceNumber\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" placeholder=\"StatementReference\"");

WriteLiteral(" id=\"StatementReferenceInputText\"");

WriteLiteral(" title=\"StatementReference\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" placeholder=\"PostedBy\"");

WriteLiteral(" id=\"PostedByInputText\"");

WriteLiteral(" title=\"PostedBy\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(" id=\"ShowButton\"");

WriteLiteral(">Show</div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        " +
"<table");

WriteLiteral(" id=\"AdjustmentView\"");

WriteLiteral(" class=\"ui table segment\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th>Actions</th>
                    <th>TranId</th>
                    <th>TranCode</th>
                    <th>Value Date</th>
                    <th>Book Date</th>
                    <th>Ref#</th>
                    <th>Statement Reference</th>
                    <th>Posted By</th>
                    <th>Office</th>
                    <th>Status</th>
                    <th>Verified By</th>
                    <th>Verified On</th>
                    <th>Reason</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

    </div>
</div>
<div");

WriteLiteral(" class=\"ui large advice modal\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"close icon\"");

WriteLiteral("></i>\r\n    <iframe></iframe>\r\n</div>\r\n\r\n<script>\r\n    function displayTable(targe" +
"t, model) {\r\n        target.find(\"tbody\").html(\"\");\r\n        function getCell(te" +
"xt) {\r\n            var cell = $(\"<td />\");\r\n\r\n            cell.text(text || \"\");" +
"\r\n\r\n            return cell;\r\n        };\r\n\r\n        function getActionCell(tranI" +
"d) {\r\n            var cell = $(\"<td />\");\r\n\r\n            var checklistAnchor = $" +
"(\"<a title=\'Checklist Window\'><i class=\'list icon\'></i></a>\");\r\n            chec" +
"klistAnchor.attr(\"href\", \"/dashboard/inventory/tasks/adjustments/checklist/\" + t" +
"ranId);\r\n\r\n            var journalAdviceAnchor = $(\"<a title=\'View Journal Advic" +
"e\'><i class=\'print icon\'></i></a>\");\r\n            journalAdviceAnchor.attr(\"href" +
"\", \"javascript:void(0);\");\r\n            journalAdviceAnchor.attr(\"onclick\", \"sho" +
"wJournalAdvice(\" + tranId + \");\");\r\n\r\n            var inventoryAdviceAnchor = $(" +
"\"<a title=\'View Purchase Invoice\'><i class=\'zoom icon\'></i></a>\");\r\n            " +
"inventoryAdviceAnchor.attr(\"href\", \"javascript:void(0);\");\r\n            inventor" +
"yAdviceAnchor.attr(\"onclick\", \"showAdjustment(\" + tranId + \");\");\r\n\r\n\r\n         " +
"   cell.append(checklistAnchor);\r\n            cell.append(journalAdviceAnchor);\r" +
"\n            cell.append(inventoryAdviceAnchor);\r\n            return cell;\r\n    " +
"    };\r\n\r\n        $.each(model, function () {\r\n            var item = this;\r\n\r\n " +
"           var row = $(\"<tr />\");\r\n\r\n            row.append(getActionCell(item.T" +
"ransactionMasterId));\r\n            row.append(getCell(item.TransactionMasterId))" +
";\r\n            row.append(getCell(item.TransactionCode));\r\n            row.appen" +
"d(getCell(item.ValueDate));\r\n            row.append(getCell(item.BookDate));\r\n  " +
"          row.append(getCell(item.ReferenceNumber));\r\n            row.append(get" +
"Cell(item.StatementReference));\r\n            row.append(getCell(item.PostedBy));" +
"\r\n            row.append(getCell(item.Office));\r\n            row.append(getCell(" +
"item.Status));\r\n            row.append(getCell(item.VerifiedBy));\r\n            r" +
"ow.append(getCell(item.VerifiedOn));\r\n            row.append(getCell(item.Reason" +
"));\r\n\r\n            target.find(\"tbody\").append(row);\r\n        });\r\n    };\r\n    f" +
"unction processQuery() {\r\n        function getModel() {\r\n            var model =" +
" window.serializeForm($(\"#Annotation\"));\r\n            model.Book = \"Inventory Ad" +
"justment\";\r\n            return model;\r\n        };\r\n\r\n        function displayGri" +
"d(target) {\r\n            function request(model) {\r\n                var url = \"/" +
"dashboard/finance/tasks/journal/view\";\r\n                var data = JSON.stringif" +
"y(model);\r\n                return window.getAjaxRequest(url, \"POST\", data);\r\n   " +
"         };\r\n\r\n            var model = getModel();\r\n\r\n\r\n            var ajax = r" +
"equest(model);\r\n\r\n            ajax.success(function (response) {\r\n              " +
"  displayTable(target, response);\r\n                target.removeClass(\"loading\")" +
";\r\n            });\r\n\r\n            ajax.fail(function (xhr) {\r\n                al" +
"ert(JSON.stringify(xhr));\r\n            });\r\n        };\r\n\r\n        var view = $(\"" +
"#AdjustmentView\").addClass(\"loading\");\r\n\r\n        displayGrid(view);\r\n    };\r\n\r\n" +
"    $(\"#ShowButton\").unbind(\"click\").bind(\"click\", function () {\r\n        proces" +
"sQuery();\r\n    });\r\n\r\n    loadDatepicker();\r\n    setTimeout(function () {\r\n     " +
"   processQuery();\r\n    }, 1000);\r\n\r\n\r\n    function showAdjustment(tranId) {\r\n  " +
"      $(\".advice.modal iframe\").attr(\"src\", \"/dashboard/reports/source/Areas/Mix" +
"ERP.Inventory/Reports/Adjustment.xml?transaction_master_id=\" + tranId);\r\n\r\n     " +
"   setTimeout(function () {\r\n            $(\".advice.modal\")\r\n                .mo" +
"dal(\'setting\', \'transition\', \'horizontal flip\')\r\n                .modal({\r\n     " +
"               blurring: true\r\n                })\r\n                .modal(\"show\"" +
");\r\n\r\n        }, 300);\r\n    };\r\n    function showJournalAdvice(tranId) {\r\n      " +
"  $(\".modal iframe\").attr(\"src\", \"/dashboard/reports/source/Areas/MixERP.Finance" +
"/Reports/JournalEntry.xml?transaction_master_id=\" + tranId);\r\n\r\n        setTimeo" +
"ut(function () {\r\n            $(\".advice.modal\")\r\n                .modal(\'settin" +
"g\', \'transition\', \'horizontal flip\')\r\n                .modal({\r\n                " +
"    blurring: true\r\n                })\r\n                .modal(\"show\");\r\n\r\n     " +
"   }, 300);\r\n    };\r\n\r\n</script>");

        }
    }
}
#pragma warning restore 1591
